config/routes.rb
require 'sidekiq/web'


Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Rswag::Ui::Engine => '/api-docs'
    mount Rswag::Api::Engine => '/api-docs'
    mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app
  end


  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
 
  # post "/blogs", to:"blogs#create"
  # get "/blogs/new", to:"blogs#new"
  # get "/blogs/:id", to:"blogs#show", as: :show
  # delete "/blogs/:id", to: "blogs#destroy"
  # get "/blogs/:id/edit", to: "blogs#edit", as: :blog
  # patch "/blogs/:id/edit", to: "blogs#update"
  get "/blogs/:id/shared", to: "blogs#share_blog", as: :share
  get "/blogs/scheduled", to: "blogs#scheduled", as: :scheduled
  get "/blogs/draft", to: "blogs#draft", as: :draft
  get "/blogs/archived", to: "blogs#archived", as: :archived
  patch "/blogs/:id/archive", to: "blogs#archive", as: :archive_blog
  # get "/blogs/search", to: "blogs#search", as: :search
  

  resources :blogs do
    collection do
      get :search
      patch :bulk_archive_blogs 
      
    end
    resources :comments, only: [:create, :update]
    
  end
  root "blogs#index"

  
  
  #This will match any GET request with an unmatched path
  # get "*path", to: "blogs#index"

  get '*path' => redirect('/')
  
end

app/models/blog.rb
class Blog < ApplicationRecord
  
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  # def should_generate_new_friendly_id?
  #   new_record?
  # end

  has_rich_text :content
  has_many :comments

  validates :title, presence: true, length: {maximum: 120}
  validates :content, presence: true
  # validates :published_at, comparison: {greater_than_or_equal_to: Time.current, message: "can't be in past"}, allow_nil: true
  
  scope :draft, -> { where(published_at: nil)}
  scope :published, -> { where("published_at <= ?", Time.current) }
  scope :scheduled, -> { where("published_at > ?", Time.current)}
  scope :archived, -> { where(archived: true)}

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end

  def self.search(search)
    if search
      where('LOWER(title) LIKE ?', "%#{search.downcase}%")
    else
      all
    end
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  skip_before_action :verify_authenticity_token

  before_action :check_admin, except: [:index, :show, :share_blog, :search]
  before_action :authenticate_user!
  before_action :set_blog, except: [:index, :new, :create, :scheduled, :draft, :archived, :bulk_archive_blogs, :search]
  def index    
    @blogs = Blog.all.published.where(archived: false).search(params[:search]).order(published_at: :desc)
    # @pagy, @records = pagy(Product.all)
    @pagy, @blogs = pagy(@blogs)
    
    respond_to do |format|
      format.html
      format.json { render json: @blogs}
    end
    
  rescue Pagy::OverflowError
    # render :json => { :error => "Page Over Flow"}, :status => 404
    redirect_to root_path(page: 1), :status => 404
    
  end

 
  def scheduled
    @blogs = Blog.all.scheduled.order(published_at: :desc)
    @pagy, @blogs = pagy(@blogs)
    
    respond_to do |format|
      format.html
      format.json { render json: @blogs}
    end
    
  rescue Pagy::OverflowError
    # render :json => { :error => "Page Over Flow"}, :status => 404
    redirect_to root_path(page: 1), :status => 404
   
  end

  def draft
    @blogs = Blog.all.draft.order(created_at: :desc)
    @pagy, @blogs = pagy(@blogs) 
   
    respond_to do |format|
      format.html
      format.json { render json: @blogs}
    end
    
  rescue Pagy::OverflowError
    # render :json => { :error => "Page Over Flow"}, :status => 404
    redirect_to root_path(page: 1), :status => 404
   
  end

  def archived
    @blogs = Blog.all.archived.order(updated_at: :desc)
    @pagy, @blogs = pagy(@blogs)
 
    respond_to do |format|
      format.html
      format.json { render json: @blogs}
    end
    
  rescue Pagy::OverflowError
    # render :json => { :error => "Page Over Flow"}, :status => 404
    redirect_to root_path(page: 1), :status => 404
  end

  def show
    if request.path != blog_path(@blog)
      redirect_to @blog, status: :moved_permanently
    end
      respond_to do |format|
        format.html
        format.json { render json: @blog}
      end
  end

  def new
    @blog = Blog.new
  end

  def create
    if BlogCreateJob.perform_async(blog_params.as_json)
      # render :json => {success: blog_params.as_json}, :status => 201
      redirect_to root_path, :status => 201
    # else
    #   render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if !BlogUpdateJob.perform_async(params[:id], blog_params.as_json).nil?
      redirect_to blog_path(@blog), :status => 202

    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @blog.destroy
      redirect_to root_path
    else
      render :show, status: :unprocessable_entity
    end
  end

  def share_blog
    # BlogMailer.share_blog(@blog, current_user).deliver_later
    BlogMailer.with(user: current_user, blog: @blog).share_blog(@blog, current_user).deliver_later
    # Any key-value pair passed to with just becomes the params for the mailer action. So with(user: @user, account: @user.account) makes params[:user] and params[:account] available in the mailer action. Just like controllers have params.

    redirect_to blog_path(@blog)
  end

  def archive    
    if !BlogArchiveJob.perform_async(params[:id]).nil?
      redirect_to blog_path(@blog), :status => 202
    else
      render :show, status: :unprocessable_entity
    end

  end

  def bulk_archive_blogs
    respond_to do |format|
      @blogs = Blog.where(id: params[:blog_ids])
      @blogs.update_all(archived: true)

      format.js
    end
  end

  def search
    # Debugger
    # @posts = Blog.where("LOWER(title) LIKE ?", "%#{params[:search].downcase}%")

    respond_to do |format|
      # @posts = Blog.where("LOWER(title) LIKE ?", "%#{params[:search].downcase}%")
      @posts = Blog.all.published.where(archived: false).order(published_at: :desc).where("LOWER(title) LIKE ?", "%#{params[:search].downcase}%")
      @post_count = @posts.count
      @pagy, @posts = pagy(@posts)
    # rescue Pagy::OverflowError
    #   redirect_to root_path(page: 1)
      format.js
    end
    rescue Pagy::OverflowError
      redirect_to root_path(page: 1)
  end

  private 
  def check_admin
    if user_signed_in? && current_user && current_user.is_admin==false
      redirect_to root_path, :status => 405
      # render :json => { :error => "Method Not Allowed"}, :status => 405
    end
  end

  def set_blog
    @blog = user_signed_in? ? Blog.friendly.find(params[:id]) : Blog.friendly.published.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    # render :json => { :error => "Record Not Found"}, :status => 404
    redirect_to root_path, :status => 404
  end

  def blog_params
    params.require(:blog).permit(:title,:content,:archived,:published_at)
    
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_cards.html.erb
<div class="w-full flex flex-col items-center text-center text-gray-900">
<%if current_user.is_admin? && controller_name == 'blogs' && action_name == 'index' || action_name == 'search' %>
      <h1 class="text-4xl font-extrabold mb-4"><%= "#{blog_type}" %></h1>


    <div class="admin-buttons my-2 flex items-center p-2">
      
      <div class="select-all-button">
        <input type="checkbox" id="select-all-blogs">
        <label>Select All</label>
      </div>
      
      <span class="mx-2 text-1xl ">|</span>
      <br />
      <button class="text-white  rounded-lg border-2 border-black bg-blue-800 px-2 py-0.5 hover:bg-violet-600 focus focus:ring focus:ring-violet-300 active:bg-violet-700" type="button" , id="archive-blogs">Archive Blogs</button>
    </div>
        
    <div class="blog-list w-4/5 text-start border-2 border-gray-900 py-4 px-4">
    <ul class="admin list-none space-y-4 ">
    <% blogs.each do |blog| %>
    <% if blog.archived == blog_hide%> 
     
        <div class="w-full content hover:border-2 p-4 border-gray-900 bg-white hover:bg-gray-200 active:bg-gray-400 my-2 " id="blog_div_<%= blog.id%>">
          <h2 class="text-lg"><li><input type="checkbox" class="blog-select-check mr-2" id="blog_<%= blog.id%>" data-blog-id= <%= blog.id%> />
      <%= link_to blog_path(blog), class: "card hover:bg-gray-200 active:bg-gray-400" do %>
          <%=blog.title%></li></h2>
        <p><%#=blog.content%></p>
        </div>

      <%end%>
    <%end%>
    <%end%>      
    </ul>
    </div>

<%else%>
  <div class="w-full flex flex-col items-center text-center">
  <h1 class="text-4xl font-extrabold mb-4"><%= "#{blog_type}" %></h1>

    <div class="blog-list w-4/5 text-start border-2 border-gray-900 py-4 px-4">
    <ul class="admin list-none space-y-4 ">
    <% blogs.each do |blog| %>
    <% if blog.archived == blog_hide%>
      
        <div class="w-full content hover:border-2 p-4 border-gray-900 bg-white hover:bg-gray-200 active:bg-gray-400 my-2 " id="blog_div_<%= blog.id%>">
          <h2 class="text-lg"><li>
      <%= link_to blog_path(blog), class: "card hover:bg-gray-200 active:bg-gray-400" do %>
          <%=blog.title%></li></h2>
        <p><%#=blog.content%></p>
        </div>

      <%end%>
    <%end%>
    <%end%>      
    </ul>
    </div>

<%end%>

  <div class="pagination bottom m-4 p-4">
    <hr>
   <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
  </div>
</div>

app/views/blogs/_form.html.erb
<div class="form mt-5 border-2 border-gray-900 p-8">
    <%= form_with model:model_name do |form|%>
      <div style="color: red;" >
        <% if form.object.errors.any? %>
          <% form.object.errors.each do |err| %>
            <div class="bg-orange-100 border-l-4 border-orange-500 text-orange-700 p-4 my-1" role="alert" id="alert">
              <p class="alert"><%= err.full_message%></p>   
            </div>
          <% end %>
        <%end%>
      </div>

     <div class="form-mid bg-white p-5 border-2 space-y-5">
      <div>
      <%= form.label :title%>
      <%= form.text_field :title%>
      </div>

      <div>
      <%= form.label :content%>
      <%= form.rich_text_area :content%>
      </div>

      <div>
      <%= form.label :published_at%>
      <%= form.datetime_select :published_at, include_blank: true, start_year: Time.now.year, time_zone: 'New Delhi'%>
      </div>
    </div>

    <div class="form-bottom mt-2 mx-auto text-center">  
      <%= form.submit "Save", :class=> "rounded-lg border-2 bg-slate-500 px-3 py-1 text-white hover:bg-slate-400 hover:text-black my-2" %>
    <%end%>
    </div>
</div>

app/views/blogs/archived.html.erb
<%= render partial: "cards", locals: {blog_type: "Archives", blogs: @blogs, blog_hide: true} %>

app/views/blogs/bulk_archive_blogs.js.erb
<% params[:blog_ids].each do |blog_id| %>
  $("#blog_div_<%= blog_id %>").remove();
<% end %>

app/views/blogs/draft.html.erb
<%= render partial: "cards", locals: {blog_type: "Drafts", blogs: @blogs, blog_hide: false} %>

app/views/blogs/edit.html.erb
<div class="main mx-auto flex flex-col items-center justify-center py-5">
    <div class="head text-2xl font-extrabold">
      <h1>Edit Blog</h1>
    </div>

  <%= render partial: "form", locals: {model_name: @blog} %>

  <div class="text-blue-600 my-6 font-extrabold flex flex-row items-center">
    <div>
      <%= button_to "Delete", blog_path, method: :delete, data: {turbo_confirm: "You want to delete Blog: #{@blog.title}"}, class: " underline my-2 mx-5" %>
    </div>
    <div>
      <%= link_to "Back", :back, class: "back-btn underline my-2 mx-5" %>
    </div>
  </div>

</div>

app/views/blogs/index.html.erb
<%= form_tag blogs_path, :method => 'get', :id => "blogs_search" do %>
  <div class="w-3/5 mx-auto mt-3 relative">
    <%= text_field_tag :search, params[:search], :id => "search_field", :class=> "bg-white rounded-full py-2 px-4 pl-12 w-full focus:border-2 focus:border-gray-900", :placeholder=>"Search" %>
      <div class="absolute top-0 left-0 mt-2 ml-2">
        <span class="inline-block h-6 w-6 rounded-full bg-gray-300"></span> 
      </div>
  </div>
  
  <div id="blogs">
  <%= render partial: "cards", locals: {blog_type: "", blogs: @blogs, blog_hide: false} %>
  </div>

<% end %>

<%#= render partial: "cards", locals: {blog_type: "", blogs: @blogs, blog_hide: false} %>

app/views/blogs/new.html.erb
<div class="main mx-auto flex flex-col items-center justify-center py-5">
    <div class="head text-2xl font-extrabold">
      <h1>Add New Blog To Your Collection</h1>
    </div>

<%= render partial: "form", locals: {model_name: @blog} %>
<div class="text-blue-600 my-6 font-extrabold flex flex-row items-center">
    <div>
      <%= link_to "Back", :back, class: "back-btn underline my-2 mx-5" %>
    </div>
  </div>
</div>

app/views/blogs/scheduled.html.erb
<%= render partial: "cards", locals: {blog_type: "Scheduled", blogs: @blogs, blog_hide: false} %>

app/views/blogs/search.js.erb
if ("<%=escape_javascript(@post_count) %>" > 0){
  $("#blogs").html("<%= j render partial: 'cards', locals: {blog_type: '', blogs: @posts, blog_hide: false} %>");
  }
else{
   $("#blogs").html("<h2>No Result Found</h2>");
}
//"<%=escape_javascript("<h2>No Result Found</h2>")%>"

app/views/blogs/show.html.erb
  <div class="w-full flex flex-col items-center text-center text-gray-900">
      <h1 class="text-4xl font-extrabold mb-4"><%=@blog.title%></h1>
      
      <div class="blog-list w-4/5 text-start border-2 border-gray-900 py-4 px-4 bg-white rounded-lg">
        <p><%=@blog.content%></p>
      </div>
  
  
      <div class="btns mt-2 space-y-3">
          <div class="share-btn">
            <%= button_to "Share it with me", share_path, method: :get, :class=>"mt-2 rounded-lg border-2 border-white bg-blue-800 px-3 py-1 text-white hover:bg-blue-600 hover:ring-2 ring-blue-200" %>
          </div>
          
          <% if current_user.is_admin?%>
              <div class="space-x-3 flex justify-center">
                <%= button_to "Edit", edit_blog_path, method: :get, :class=>"text-blue-800 hover:underline" %>
                <%#= button_to "Delete", blog_path, method: :delete, data: {turbo_confirm: "You want to delete Blog: #{@blog.title}"}%>
                <%= button_to "#{ @blog.archived ? "Unarchive" : "Archive"}", archive_blog_path(@blog), method: :patch, :class=>"text-blue-800 hover:underline"%>
              </div>

              <div class="text-blue-600 my-6 font-extrabold items-center">
                  <div>
                    <%= link_to "Back", :back, class: "back-btn underline my-2 mx-5" %>
                  </div>
              </div>
            <%end%>
      </div>

      <div class="comments-sec p-4 w-full md:flex md:flex-col md:items-center ">
          <div class="comment-form flex flex-col items-center align-middle md:w-1/2">
            <hr class="h-0.5 w-full bg-black my-2" />
            <%= render partial: "comments/form"%>
          </div>
          <div class="comments-head flex items-start mx-2 border-y-2 mt-4 border-gray-400 p-2 md:w-1/2">
              <h4 class="text-gray-500">Comments: <small><%=@blog.comments.where(is_archived: false).count%></small></h4>
          </div>
              <%= render @blog.comments.order(created_at: :desc) %>
      </div>
  </div>