config/routes.rb
require 'sidekiq/web'


Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Rswag::Ui::Engine => '/api-docs'
    mount Rswag::Api::Engine => '/api-docs'
    mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app
  end


  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
 
  # post "/blogs", to:"blogs#create"
  # get "/blogs/new", to:"blogs#new"
  # get "/blogs/:id", to:"blogs#show", as: :show
  # delete "/blogs/:id", to: "blogs#destroy"
  # get "/blogs/:id/edit", to: "blogs#edit", as: :blog
  # patch "/blogs/:id/edit", to: "blogs#update"
  get "/blogs/:id/shared", to: "blogs#share_blog", as: :share
  get "/blogs/scheduled", to: "blogs#scheduled", as: :scheduled
  get "/blogs/draft", to: "blogs#draft", as: :draft
  get "/blogs/archived", to: "blogs#archived", as: :archived
  patch "/blogs/:id/archive", to: "blogs#archive", as: :archive_blog
  # get "/blogs/search", to: "blogs#search", as: :search
  

  resources :blogs do
    collection do
      get :search
      patch :bulk_archive_blogs 
      
    end
    resources :comments, only: [:create, :update]
    
  end
  root "blogs#index"

  
  
  #This will match any GET request with an unmatched path
  # get "*path", to: "blogs#index"

  get '*path' => redirect('/')
  
end

app/views/shared/_footer.html.erb
<footer class="bg-gray-900 w-full">
  <div class="h-fit py-2 flex justify-center">
    <p class="text-lg text-gray-400">
      © 2023 Bloggits
    </p>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="bg-gray-900 text-gray-400 dark:bg-gray-900 md:sticky w-full z-20 top-0 left-0 border-b border-gray-200 dark:border-gray-600">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
  <%= link_to image_tag("bloggits-logo.png", class:"h-10 mr-3 w-fit", alt:"Bloggits Logo"), root_path %>
  <% if  user_signed_in? && current_user.is_admin? %>
    <%= link_to new_blog_path, class: "flex items-center" do %>
    <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-gray-400">Create New Blog</span>
    <% end %>
  <%else%>
    <%= link_to root_path, class: "flex items-center" do %>
    <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-gray-400">Bloggits</span>
    <% end %>
  <% end %>

    <!-- Toggle button for small screens -->
    <button class="flex items-center justify-center w-10 h-10 rounded-md md:hidden" id="menu-button">
      <span class="sr-only">Toggle menu</span>
      <svg class="w-6 h-6" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path stroke="currentColor" stroke-width="2" stroke-linecap="round" d="M4 6h16M4 12h16M4 18h16"></path>
      </svg>
    </button>

    <div class="items-center justify-between w-full md:flex md:w-auto md:order-1" id="navbar-sticky">
      <ul class="flex flex-col p-4 md:p-0 mt-4 font-medium border border-gray-100 rounded-lg bg-gray-100 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-gray-900 dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700 list-none text-lg">
        <% if user_signed_in? %>
            <li>
              <%= link_to "Home", root_path, class: "block py-2 pl-3 pr-4 text-gray-400  rounded md:bg-transparent  md:p-0 md:dark:text-blue-500" %>
            </li>
            
          <% if current_user.is_admin %>
            <li>
              <%= link_to "Scheduled", scheduled_path, class: "block py-2 pl-3 pr-4 text-gray-400  rounded md:bg-transparent  md:p-0 md:dark:text-blue-500" %>
            </li>
            <li>
              <%= link_to "Drafts", draft_path, class: "block py-2 pl-3 pr-4 text-gray-400  rounded md:bg-transparent  md:p-0 md:dark:text-blue-500" %>
            </li>
            <li>
              <%= link_to "Archives", archived_path, class: "block py-2 pl-3 pr-4 text-gray-400  rounded md:bg-transparent  md:p-0 md:dark:text-blue-500" %>
            </li>
            <li>
              <%= link_to "Admin Panel", rails_admin_path, class: "block py-2 pl-3 pr-4 text-gray-400  rounded md:bg-transparent  md:p-0 md:dark:text-blue-500" %>
            </li>
          <% end %>
          <li>
            <%= link_to "Edit Profile", edit_user_registration_path, class: "block py-2 pl-3 pr-4 text-gray-400  rounded md:bg-transparent  md:p-0 md:dark:text-blue-500" %>
          </li>
          <li>
            <%= button_to "Log-Out", destroy_user_session_path, method: :delete, class: "block py-2 pl-3 pr-4 text-gray-400  rounded md:bg-transparent  md:p-0 md:dark:text-blue-500" %>
          </li>

        <% else %> 
           <li>  <%= link_to "Log-In", new_user_session_path, class: "block py-2 pl-3 pr-4 text-gray-400  rounded md:bg-transparent  md:p-0 md:dark:text-blue-500" %></li>
           <li><%= link_to "Sign-Up", new_user_registration_path, class: "block py-2 pl-3 pr-4 text-gray-400  rounded md:bg-transparent  md:p-0 md:dark:text-blue-500" %></li>

           <li><%#= button_to "Sign in with Twitter", user_twitter_omniauth_authorize_path, data: { turbo: false }, class: "block py-2 pl-3 pr-4 text-gray-400  rounded md:bg-transparent  md:p-0 md:dark:text-blue-500" %></li>

           <li><%#= button_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path, data: { turbo: false }, class: "block py-2 pl-3 pr-4 text-gray-400  rounded md:bg-transparent  md:p-0 md:dark:text-blue-500" %></li>

           <li><%#= button_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, data: { turbo: false }, class: "block py-2 pl-3 pr-4 text-gray-400  rounded md:bg-transparent  md:p-0 md:dark:text-blue-500" %></li>

           <li><%#= button_to "Sign in with LinkedIn", user_linkedin_omniauth_authorize_path, data: { turbo: false }, class: "block py-2 pl-3 pr-4 text-gray-400  rounded md:bg-transparent  md:p-0 md:dark:text-blue-500" %></li>
        <% end %>
     </ul>
   </div>
  </div>
</nav>